import * as path from 'node:path';
import {
  CfnOutput,
  Duration,
  Fn,
  RemovalPolicy,
  Stack,
  StackProps,
} from 'aws-cdk-lib';
import * as apigwv2 from 'aws-cdk-lib/aws-apigatewayv2';
import * as apigwv2_integrations from 'aws-cdk-lib/aws-apigatewayv2-integrations';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface OtpServiceStackProps extends StackProps {
  /** Verified SES sender identity (the email's From address). Non-secret. */
  readonly senderEmail: string;
}

/**
 * All infrastructure for the email OTP service:
 *  - DynamoDB table with TTL-based auto-expiry of codes
 *  - Secrets Manager secret holding a randomly generated HMAC pepper (generated by CDK)
 *  - Two Lambda functions (request / verify) bundled with esbuild
 *  - HTTP API (API Gateway v2) with throttling and access logging
 *  - Least-privilege IAM grants wiring it together
 */
export class OtpServiceStack extends Stack {
  constructor(scope: Construct, id: string, props: OtpServiceStackProps) {
    super(scope, id, props);

    // --- Persistence ---------------------------------------------------------
    const table = new dynamodb.Table(this, 'OtpTable', {
      partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: 'expiresAt',
      pointInTimeRecoverySpecification: { pointInTimeRecoveryEnabled: true },
      encryption: dynamodb.TableEncryption.AWS_MANAGED,
      // Temp/demo account → clean teardown. Switch to RETAIN for real production.
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // --- Server-side HMAC pepper (generated, never hard-coded) ---------------
    const pepperSecret = new secretsmanager.Secret(this, 'OtpPepper', {
      description: 'HMAC pepper for OTP code hashing (generated by CDK).',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({}),
        generateStringKey: 'pepper',
        passwordLength: 64,
        excludePunctuation: true,
      },
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // --- Shared Lambda configuration ----------------------------------------
    const commonEnv = {
      TABLE_NAME: table.tableName,
      SENDER_EMAIL: props.senderEmail,
      PEPPER_SECRET_ARN: pepperSecret.secretArn,
      CODE_TTL_SECONDS: '600',
      CODE_LENGTH: '6',
      MAX_VERIFY_ATTEMPTS: '5',
      RESEND_COOLDOWN_SECONDS: '60',
      MAX_SENDS_PER_WINDOW: '5',
      SEND_WINDOW_SECONDS: '3600',
      POWERTOOLS_SERVICE_NAME: 'ses-otp-service',
      POWERTOOLS_LOG_LEVEL: 'INFO',
    };

    const makeFn = (logicalId: string, entry: string): NodejsFunction => {
      const logGroup = new logs.LogGroup(this, `${logicalId}Logs`, {
        retention: logs.RetentionDays.TWO_WEEKS,
        removalPolicy: RemovalPolicy.DESTROY,
      });
      return new NodejsFunction(this, logicalId, {
        runtime: lambda.Runtime.NODEJS_20_X,
        architecture: lambda.Architecture.ARM_64,
        entry: path.join(__dirname, '..', 'src', 'handlers', entry),
        handler: 'handler',
        memorySize: 256,
        timeout: Duration.seconds(15),
        environment: commonEnv,
        tracing: lambda.Tracing.ACTIVE,
        logGroup,
        bundling: {
          minify: true,
          sourceMap: true,
          target: 'node20',
          // AWS SDK v3 is provided by the Node 20 runtime; do not bundle it.
          externalModules: ['@aws-sdk/*'],
        },
      });
    };

    const requestFn = makeFn('RequestOtpFn', 'request-otp.ts');
    const verifyFn = makeFn('VerifyOtpFn', 'verify-otp.ts');
    // Serves the browser UI at `GET /`. Stateless — no table/secret/SES access needed.
    const webFn = makeFn('WebFn', 'web.ts');

    // --- Least-privilege IAM -------------------------------------------------
    // request: read+write the table, read the pepper, send mail as the verified sender.
    table.grantReadWriteData(requestFn);
    pepperSecret.grantRead(requestFn);
    requestFn.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ['ses:SendEmail'],
        resources: ['*'],
        conditions: {
          StringEquals: { 'ses:FromAddress': props.senderEmail },
        },
      }),
    );

    // verify: read+write the table (to bump attempts / consume), read the pepper. No SES.
    table.grantReadWriteData(verifyFn);
    pepperSecret.grantRead(verifyFn);

    // --- HTTP API ------------------------------------------------------------
    const accessLogGroup = new logs.LogGroup(this, 'ApiAccessLogs', {
      retention: logs.RetentionDays.TWO_WEEKS,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    const httpApi = new apigwv2.HttpApi(this, 'OtpHttpApi', {
      description: 'Email OTP service API',
      createDefaultStage: false,
    });

    httpApi.addRoutes({
      path: '/v1/otp/request',
      methods: [apigwv2.HttpMethod.POST],
      integration: new apigwv2_integrations.HttpLambdaIntegration(
        'RequestIntegration',
        requestFn,
      ),
    });
    httpApi.addRoutes({
      path: '/v1/otp/verify',
      methods: [apigwv2.HttpMethod.POST],
      integration: new apigwv2_integrations.HttpLambdaIntegration(
        'VerifyIntegration',
        verifyFn,
      ),
    });
    // Browser UI at the root path.
    httpApi.addRoutes({
      path: '/',
      methods: [apigwv2.HttpMethod.GET],
      integration: new apigwv2_integrations.HttpLambdaIntegration('WebIntegration', webFn),
    });

    // Explicit stage with throttling (outer guard) and access logging.
    const stage = new apigwv2.HttpStage(this, 'DefaultStage', {
      httpApi,
      stageName: 'prod',
      autoDeploy: true,
      throttle: { rateLimit: 20, burstLimit: 40 },
    });

    // Access logging is configured on the underlying CFN stage resource.
    const cfnStage = stage.node.defaultChild as apigwv2.CfnStage;
    cfnStage.accessLogSettings = {
      destinationArn: accessLogGroup.logGroupArn,
      format: JSON.stringify({
        requestId: '$context.requestId',
        ip: '$context.identity.sourceIp',
        routeKey: '$context.routeKey',
        status: '$context.status',
        integrationStatus: '$context.integration.status',
        latencyMs: '$context.responseLatency',
      }),
    };

    // --- CloudFront entry point ---------------------------------------------
    // Single public origin for both the UI and the API → same-origin, no CORS needed.
    // The HTTP API host is derived from its endpoint; `originPath: /prod` targets the stage.
    const apiDomain = Fn.select(2, Fn.split('/', httpApi.apiEndpoint));

    const apiOrigin = new origins.HttpOrigin(apiDomain, {
      originPath: `/${stage.stageName}`,
      protocolPolicy: cloudfront.OriginProtocolPolicy.HTTPS_ONLY,
    });

    const distribution = new cloudfront.Distribution(this, 'OtpDistribution', {
      comment: 'Email OTP service — UI + API entry point',
      defaultBehavior: {
        origin: apiOrigin,
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
        // POST bodies must reach Lambda untouched and responses must never be cached.
        cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
        originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
      },
    });

    // --- Outputs -------------------------------------------------------------
    new CfnOutput(this, 'SiteUrl', {
      value: `https://${distribution.distributionDomainName}/`,
      description: 'Open this in a browser to use the OTP demo UI.',
    });
    new CfnOutput(this, 'ApiBaseUrl', {
      value: stage.url,
      description: 'Direct API base URL (append /v1/otp/request | /v1/otp/verify).',
    });
    new CfnOutput(this, 'TableName', { value: table.tableName });
    new CfnOutput(this, 'PepperSecretArn', { value: pepperSecret.secretArn });
    new CfnOutput(this, 'SenderEmail', { value: props.senderEmail });
  }
}
